### ISSUE TITLE
Cannot sign in due to ECMAScript errors

### ISSUE THREAD

**Issue by hoehermann** [xblox/xamiro#8]
Upon loading the main page in Chrome for the first time after installation, an error occurs:

    xbox.js:1042 error in rpc service creation : Error
        _initService @ xbox.js:1042
        check @ xbox.js:1042
        init @ xbox.js:1041
        (anonymous) @ xbox.js:618
        initService @ index.php:197
        (anonymous) @ index.php:236
        c @ xbox.js:1369
        m @ xbox.js:1368
        q @ xbox.js:1368
        l @ xbox.js:1192
        e @ xbox.js:1193
    xbox.js:23 ReferenceError: logError is not defined
        at b._initService (xbox.js:1042)
        at b.check (xbox.js:1042)
        at b.init (xbox.js:1041)
        at b.init (xbox.js:618)
        at initService (index.php:197)
        at index.php:236
        at c (xbox.js:1369)
        at m (xbox.js:1368)
        at q (xbox.js:1368)
        at l (xbox.js:1192)

Upon clicking the "sign in" button, another error occurs.

    index.php:216 Uncaught TypeError: Cannot read property 'XApp_XIDE_Controller_UserService' of null
        at login (index.php:216)
        at HTMLButtonElement.<anonymous> (index.php:186)
        at HTMLButtonElement.dispatch (xamiro-externals.js:218)
        at HTMLButtonElement.l.handle (xamiro-externals.js:211)

Signing in is not possible.

**Comment by xblox** [comment]
Hi,
thanks for your report. looks more like a server issue to me. You have some more details from your apache/php log ? 
However, I gonna look into tomorrow. 

g

**Comment by hoehermann** [comment]
Apache log shows `/xamiro/client/src/xfile/dojo/dojo.js.map` and `/xamiro/client/src/theme/html-white/dist/css/bootstrap-select.css.map` are not being found. These files are not included in the archive https://github.com/gbaumgart/xamiro/archive/master.zip. No critical server side errors are reported. Neither are PHP-related errors.

**Comment by xblox** [comment]
Hi there, I had a look but no, my installations from github are up and running fine. 
So for now I can only request more details like php-version and server OS... 

Given the trace you gave me, it's definitely a server side problem.  

For instance, opening http://localhost/projects/xamiro/index.php?view=rpc should give you :

SMDVersion: "2.0",
description: "Xapp JSON RPC Server",
contentType: "application/json",
transport: "POST",
envelope: "JSON-RPC-2.0",
....

regards,
g

**Comment by xblox** [comment]
- make sure xamiro folder permissions are at 755
- php-6 
- php-extensions are installed: mbcrypt & FileInfo
g

**Comment by hoehermann** [comment]
Thank you. `index.php?view=rpc` showed an error message instead of failing silently. It turns out, my server was missing the PHP mbstring extension. I hereby suggest adding it to the list of dependencies. Note: On Ubuntu, fileinfo is included in php7.0-common.

**Comment by xblox** [comment]
thanks @hoehermann. will update and docs regarding this.
